- name: Deploy App to EC2
  hosts: all
  become: true
  user: ubuntu
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Pull Docker Image
      shell: docker pull dhuuthuc/lab01-fe:latest

    - name: Stop old container
      shell: docker stop my-auto-app || true

    - name: Remove old container
      shell: docker rm my-auto-app || true

    - name: Run Docker Container
      shell: docker run -d --name my-auto-app -p 8080:8080 dhuuthuc/lab01-fe:latest
